name: routineup
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# --- DEPENDENSI UTAMA APLIKASI ---
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # Penting untuk Isar di Flutter
  path_provider: ^2.1.3

  # UI Components & Utilities
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.0
  intl: # Versi dikontrol oleh flutter_localizations
  table_calendar: ^3.1.1
  fl_chart: ^0.68.0                 # <-- TAMBAHKAN INI

  # Estetika, Info & Animasi
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.0


# --- DEPENDENSI UNTUK DEVELOPMENT & BUILD ---
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

  # Linter untuk menjaga kualitas kode
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.4.0


# --- KONFIGURASI FLUTTER ---
flutter:
  uses-material-design: true
  generate: true # Mengaktifkan code generation untuk lokalisasi (l10n)

flutter_launcher_icons:
  android: true # Aktifkan untuk Android
  ios: true # Aktifkan untuk iOS
  image_path: "assets/icon/routine2.png"
  min_sdk_android: 21

flutter_native_splash:
  # Warna latar belakang untuk splash screen
  color: "#FFFFFF" # Warna untuk Light Mode (Putih)
  color_dark: "#2D2D2D" # Warna untuk Dark Mode (Abu-abu gelap)

  # Logo Anda
  image: assets/icon/routine.png # Sesuaikan dengan path logo Anda

  # Atur cara logo ditampilkan
  android_12:
    # Untuk Android 12+, logo bisa sedikit berbeda
    image: assets/icon/routine.png
    color: "#FFFFFF"
    color_dark: "#2D2D2D"

  # Anda bisa menambahkan properti lain sesuai kebutuhan
  fullscreen: true